GET http://localhost:5000/api/events

###
GET http://localhost:5000/api/events/11

###
POST http://localhost:5000/api/events
Content-Type: application/json

{
    "title" : "Nuit des étoiles",
    "description" : "C'est enfin la nuit des étoiles et nous avions hâte !",
    "date" : "2020-05-12T23:50:21.817Z",
    "site" : "Observatoire de Saint Jean Le Blanc",
    "userId": 1
}

###
PUT http://localhost:5000/api/events/12
Content-Type: application/json

{
    "title" : "Nuit des étoiles filantes",
    "description" : "C'est enfin la nuit des étoiles et nous avions hâte !",
    "date" : "2020-05-12T23:50:21.817Z",
    "site" : "Observatoire de Saint Jean Le Blanc",
    "userId": 1
}

###
DELETE http://localhost:5000/api/events/9